# Generated by Django 5.1 on 2024-08-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pseudo", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=15)),
                ("creation_date", models.DateTimeField()),
            ],
        ),
    ]
